/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArquivoRouteImport } from './routes/arquivo'
import { Route as CinemaRouteImport } from './routes/cinema'
import { Route as DocumentarioRouteImport } from './routes/documentario'
import { Route as EpisodiosRouteImport } from './routes/episodios'
import { Route as HomeRouteImport } from './routes/home'
import { Route as TrailerRouteImport } from './routes/trailer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivoRoute = ArquivoRouteImport.update({
  id: '/arquivo',
  path: '/arquivo',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemaRoute = CinemaRouteImport.update({
  id: '/cinema',
  path: '/cinema',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentarioRoute = DocumentarioRouteImport.update({
  id: '/documentario',
  path: '/documentario',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodiosRoute = EpisodiosRouteImport.update({
  id: '/episodios',
  path: '/episodios',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailerRoute = TrailerRouteImport.update({
  id: '/trailer',
  path: '/trailer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arquivo': typeof ArquivoRoute
  '/cinema': typeof CinemaRoute
  '/documentario': typeof DocumentarioRoute
  '/episodios': typeof EpisodiosRoute
  '/home': typeof HomeRoute
  '/trailer': typeof TrailerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arquivo': typeof ArquivoRoute
  '/cinema': typeof CinemaRoute
  '/documentario': typeof DocumentarioRoute
  '/episodios': typeof EpisodiosRoute
  '/home': typeof HomeRoute
  '/trailer': typeof TrailerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arquivo': typeof ArquivoRoute
  '/cinema': typeof CinemaRoute
  '/documentario': typeof DocumentarioRoute
  '/episodios': typeof EpisodiosRoute
  '/home': typeof HomeRoute
  '/trailer': typeof TrailerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arquivo'
    | '/cinema'
    | '/documentario'
    | '/episodios'
    | '/home'
    | '/trailer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arquivo'
    | '/cinema'
    | '/documentario'
    | '/episodios'
    | '/home'
    | '/trailer'
  id:
    | '__root__'
    | '/'
    | '/arquivo'
    | '/cinema'
    | '/documentario'
    | '/episodios'
    | '/home'
    | '/trailer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArquivoRoute: typeof ArquivoRoute
  CinemaRoute: typeof CinemaRoute
  DocumentarioRoute: typeof DocumentarioRoute
  EpisodiosRoute: typeof EpisodiosRoute
  HomeRoute: typeof HomeRoute
  TrailerRoute: typeof TrailerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivo': {
      id: '/arquivo'
      path: '/arquivo'
      fullPath: '/arquivo'
      preLoaderRoute: typeof ArquivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinema': {
      id: '/cinema'
      path: '/cinema'
      fullPath: '/cinema'
      preLoaderRoute: typeof CinemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentario': {
      id: '/documentario'
      path: '/documentario'
      fullPath: '/documentario'
      preLoaderRoute: typeof DocumentarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodios': {
      id: '/episodios'
      path: '/episodios'
      fullPath: '/episodios'
      preLoaderRoute: typeof EpisodiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trailer': {
      id: '/trailer'
      path: '/trailer'
      fullPath: '/trailer'
      preLoaderRoute: typeof TrailerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArquivoRoute: ArquivoRoute,
  CinemaRoute: CinemaRoute,
  DocumentarioRoute: DocumentarioRoute,
  EpisodiosRoute: EpisodiosRoute,
  HomeRoute: HomeRoute,
  TrailerRoute: TrailerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
