/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConteudoRouteImport } from './routes/conteudo'
import { Route as ApresentarNRouteImport } from './routes/apresentar.$n'
import { Route as CapituloNRouteImport } from './routes/capitulo.$n'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoRoute = ConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentarNRoute = ApresentarNRouteImport.update({
  id: '/apresentar/$n',
  path: '/apresentar/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const CapituloNRoute = CapituloNRouteImport.update({
  id: '/capitulo/$n',
  path: '/capitulo/$n',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conteudo': typeof ConteudoRoute
  '/apresentar/$n': typeof ApresentarNRoute
  '/capitulo/$n': typeof CapituloNRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conteudo': typeof ConteudoRoute
  '/apresentar/$n': typeof ApresentarNRoute
  '/capitulo/$n': typeof CapituloNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conteudo': typeof ConteudoRoute
  '/apresentar/$n': typeof ApresentarNRoute
  '/capitulo/$n': typeof CapituloNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conteudo' | '/apresentar/$n' | '/capitulo/$n'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conteudo' | '/apresentar/$n' | '/capitulo/$n'
  id: '__root__' | '/' | '/conteudo' | '/apresentar/$n' | '/capitulo/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConteudoRoute: typeof ConteudoRoute
  ApresentarNRoute: typeof ApresentarNRoute
  CapituloNRoute: typeof CapituloNRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo': {
      id: '/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof ConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentar/$n': {
      id: '/apresentar/$n'
      path: '/apresentar/$n'
      fullPath: '/apresentar/$n'
      preLoaderRoute: typeof ApresentarNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capitulo/$n': {
      id: '/capitulo/$n'
      path: '/capitulo/$n'
      fullPath: '/capitulo/$n'
      preLoaderRoute: typeof CapituloNRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConteudoRoute: ConteudoRoute,
  ApresentarNRoute: ApresentarNRoute,
  CapituloNRoute: CapituloNRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
